Added support for ti-icdi in Open OCD. My editor changes all tabs to spaces but since the original file was a mix of the two styles I've left it for consistancy.

diff --git a/summon-arm-toolchain b/summon-arm-toolchain
--- a/summon-arm-toolchain
+++ b/summon-arm-toolchain
@@ -51,50 +51,50 @@ FETCH_NO_CERTCHECK="--no-check-certificate "
 ##############################################################################
 
 while [ $# -gt 0 ]; do
-	case $1 in
-		TARGET=*)
-		TARGET=$(echo $1 | sed 's,^TARGET=,,')
-		;;
-		PREFIX=*)
-		PREFIX=$(echo $1 | sed 's,^PREFIX=,,')
-		;;
-		DARWIN_OPT_PATH=*)
-		DARWIN_OPT_PATH=$(echo $1 | sed 's,^DARWIN_OPT_PATH=,,')
-		;;
-		SUDO=*)
-		SUDO=$(echo $1 | sed 's,^SUDO=,,')
-		;;
-		QUIET=*)
-		QUIET=$(echo $1 | sed 's,^QUIET=,,')
-		;;
-		USE_LINARO=*)
-		USE_LINARO=$(echo $1 | sed 's,^USE_LINARO=,,')
-		;;
-		OOCD_EN=*)
-		OOCD_EN=$(echo $1 | sed 's,^OOCD_EN=,,')
-		;;
-		OOCD_GIT=*)
-		OOCD_GIT=$(echo $1 | sed 's,^OOCD_GIT=,,')
-		;;
-		LIBSTM32_EN=*)
-		LIBSTM32_EN=$(echo $1 | sed 's,^LIBSTM32_EN=,,')
-		;;
-		LIBOPENCM3_EN=*)
-		LIBOPENCM3_EN=$(echo $1 | sed 's,^LIBOPENCM3_EN=,,')
-		;;
-		DEFAULT_TO_CORTEX_M3=*)
-		DEFAULT_TO_CORTEX_M3=$(echo $1 | sed 's,^DEFAULT_TO_CORTEX_M3=,,')
-		;;
-		CPUS=*)
-		CPUS=$(echo $1 | sed 's,^CPUS=,,')
-		;;
-		*)
-		echo "Unknown parameter: $1"
-		exit 1
-		;;
-	esac
+    case $1 in
+        TARGET=*)
+        TARGET=$(echo $1 | sed 's,^TARGET=,,')
+        ;;
+        PREFIX=*)
+        PREFIX=$(echo $1 | sed 's,^PREFIX=,,')
+        ;;
+        DARWIN_OPT_PATH=*)
+        DARWIN_OPT_PATH=$(echo $1 | sed 's,^DARWIN_OPT_PATH=,,')
+        ;;
+        SUDO=*)
+        SUDO=$(echo $1 | sed 's,^SUDO=,,')
+        ;;
+        QUIET=*)
+        QUIET=$(echo $1 | sed 's,^QUIET=,,')
+        ;;
+        USE_LINARO=*)
+        USE_LINARO=$(echo $1 | sed 's,^USE_LINARO=,,')
+        ;;
+        OOCD_EN=*)
+        OOCD_EN=$(echo $1 | sed 's,^OOCD_EN=,,')
+        ;;
+        OOCD_GIT=*)
+        OOCD_GIT=$(echo $1 | sed 's,^OOCD_GIT=,,')
+        ;;
+        LIBSTM32_EN=*)
+        LIBSTM32_EN=$(echo $1 | sed 's,^LIBSTM32_EN=,,')
+        ;;
+        LIBOPENCM3_EN=*)
+        LIBOPENCM3_EN=$(echo $1 | sed 's,^LIBOPENCM3_EN=,,')
+        ;;
+        DEFAULT_TO_CORTEX_M3=*)
+        DEFAULT_TO_CORTEX_M3=$(echo $1 | sed 's,^DEFAULT_TO_CORTEX_M3=,,')
+        ;;
+        CPUS=*)
+        CPUS=$(echo $1 | sed 's,^CPUS=,,')
+        ;;
+        *)
+        echo "Unknown parameter: $1"
+        exit 1
+        ;;
+    esac
 
-	shift # shifting parameter list to access the next one
+    shift # shifting parameter list to access the next one
 done
 
 echo "Settings used for this build are:"
@@ -115,27 +115,27 @@ echo "CPUS=$CPUS"
 # Version and download url settings section
 ##############################################################################
 if [ ${USE_LINARO} == 0 ] ; then
-	# For FSF GCC:
-	GCCVERSION=4.7.2
-	GCC=gcc-${GCCVERSION}
-	GCCURL=http://ftp.gnu.org/gnu/gcc/${GCC}/${GCC}.tar.gz
+    # For FSF GCC:
+    GCCVERSION=4.7.2
+    GCC=gcc-${GCCVERSION}
+    GCCURL=http://ftp.gnu.org/gnu/gcc/${GCC}/${GCC}.tar.gz
 
-	# For FSF GDB:
-	GDBVERSION=7.5.1
-	GDB=gdb-${GDBVERSION}
-	GDBURL=http://ftp.gnu.org/gnu/gdb/${GDB}.tar.bz2
+    # For FSF GDB:
+    GDBVERSION=7.5.1
+    GDB=gdb-${GDBVERSION}
+    GDBURL=http://ftp.gnu.org/gnu/gdb/${GDB}.tar.bz2
 else
-	# For Linaro GCC:
-	GCCRELEASE=4.7-2013.01
-	GCCVERSION=4.7-2013.01
-	GCC=gcc-linaro-${GCCVERSION}
-	GCCURL=http://launchpad.net/gcc-linaro/4.7/${GCCRELEASE}/+download/${GCC}.tar.bz2
+    # For Linaro GCC:
+    GCCRELEASE=4.7-2013.01
+    GCCVERSION=4.7-2013.01
+    GCC=gcc-linaro-${GCCVERSION}
+    GCCURL=http://launchpad.net/gcc-linaro/4.7/${GCCRELEASE}/+download/${GCC}.tar.bz2
 
-	# For Linaro GDB:
-	GDBRELEASE=7.5-2012.12-1
-	GDBVERSION=7.5-2012.12-1
-	GDB=gdb-linaro-${GDBVERSION}
-	GDBURL=http://launchpad.net/gdb-linaro/7.5/${GDBRELEASE}/+download/${GDB}.tar.bz2
+    # For Linaro GDB:
+    GDBRELEASE=7.5-2012.12-1
+    GDBVERSION=7.5-2012.12-1
+    GDB=gdb-linaro-${GDBVERSION}
+    GDBURL=http://launchpad.net/gdb-linaro/7.5/${GDBRELEASE}/+download/${GDB}.tar.bz2
 fi
 
 BINUTILS=binutils-2.23.1
@@ -156,15 +156,15 @@ LIBOPENCM3_GIT=master
 ##############################################################################
 
 if [ "x${CPUS}" == "x" ]; then
-	if which getconf > /dev/null; then
-		CPUS=$(getconf _NPROCESSORS_ONLN)
-	else
-		CPUS=1
-	fi
+    if which getconf > /dev/null; then
+        CPUS=$(getconf _NPROCESSORS_ONLN)
+    else
+        CPUS=1
+    fi
 
-	PARALLEL=-j$((CPUS + 1))
+    PARALLEL=-j$((CPUS + 1))
 else
-	PARALLEL=-j${CPUS}
+    PARALLEL=-j${CPUS}
 fi
 
 echo "${CPUS} cpu's detected running make with '${PARALLEL}' flag"
@@ -173,10 +173,10 @@ GDBFLAGS=
 BINUTILFLAGS=
 
 if [ ${DEFAULT_TO_CORTEX_M3} == 0 ] ; then
-	GCCFLAGS=
+    GCCFLAGS=
 else
-	# To default to the Cortex-M3:
-	GCCFLAGS="--with-arch=armv7-m --with-mode=thumb --with-float=soft"
+    # To default to the Cortex-M3:
+    GCCFLAGS="--with-arch=armv7-m --with-mode=thumb --with-float=soft"
 fi
 
 # Pull in the local configuration, if any
@@ -210,30 +210,30 @@ TAR=tar
 ##############################################################################
 
 case "$(uname)" in
-	Linux)
-	echo "Found Linux OS."
-	;;
-	Darwin)
-	echo "Found Darwin OS."
-	GCCFLAGS="${GCCFLAGS} \
-                  --with-gmp=${DARWIN_OPT_PATH} \
-	          --with-mpfr=${DARWIN_OPT_PATH} \
-	          --with-mpc=${DARWIN_OPT_PATH} \
-		  --with-libiconv-prefix=${DARWIN_OPT_PATH}"
-	OOCD_CFLAGS="-I/opt/mine/include -I${DARWIN_OPT_PATH}/include"
-	OOCD_LDFLAGS="-L/opt/mine/lib -L${DARWIN_OPT_PATH}/lib"
-	if gcc --version | grep llvm-gcc > /dev/null ; then
-		echo "Found you are using llvm gcc, switching to clang for gcc compile."
-		GCC_CC=llvm-gcc
-	fi
-	;;
-	CYGWIN*)
-	echo "Found CygWin that means Windows most likely."
-	;;
-	*)
-	echo "Found unknown OS. Aborting!"
-	exit 1
-	;;
+    Linux)
+    echo "Found Linux OS."
+    ;;
+    Darwin)
+    echo "Found Darwin OS."
+    GCCFLAGS="${GCCFLAGS} \
+          --with-gmp=${DARWIN_OPT_PATH} \
+          --with-mpfr=${DARWIN_OPT_PATH} \
+          --with-mpc=${DARWIN_OPT_PATH} \
+          --with-libiconv-prefix=${DARWIN_OPT_PATH}"
+    OOCD_CFLAGS="-I/opt/mine/include -I${DARWIN_OPT_PATH}/include"
+    OOCD_LDFLAGS="-L/opt/mine/lib -L${DARWIN_OPT_PATH}/lib"
+    if gcc --version | grep llvm-gcc > /dev/null ; then
+        echo "Found you are using llvm gcc, switching to clang for gcc compile."
+        GCC_CC=llvm-gcc
+    fi
+    ;;
+    CYGWIN*)
+    echo "Found CygWin that means Windows most likely."
+    ;;
+    *)
+    echo "Found unknown OS. Aborting!"
+    exit 1
+    ;;
 esac
 
 ##############################################################################
@@ -246,7 +246,7 @@ function fetch {
     if [ ! -e ${STAMPS}/$1.fetch ]; then
         if [ ! -e ${SOURCES}/$1 ]; then
             log "Downloading $1 sources..."
-	    wget -c ${FETCH_NO_PASSIVE} ${FETCH_NO_CERTCHECK} $2 && touch ${STAMPS}/$1.fetch
+            wget -c ${FETCH_NO_PASSIVE} ${FETCH_NO_CERTCHECK} $2 && touch ${STAMPS}/$1.fetch
         fi
     fi
 }
@@ -260,7 +260,7 @@ function clone {
 
     # It seems that the ref is actually a SHA as it could not be found through ls-remote
     if [ "x${GIT_SHA}" == "x" ]; then
-        local GIT_SHA=${GIT_REF}
+    local GIT_SHA=${GIT_REF}
     fi
 
     # Setting uppercase NAME variable for future use to the source file name
@@ -268,27 +268,27 @@ function clone {
 
     # Clone the repository and do all necessary operations until we get an archive
     if [ ! -e ${STAMPS}/${NAME}-${GIT_SHA}.fetch ]; then
-        # Making sure there is nothing in our way
-        if [ -e ${NAME}-${GIT_SHA} ]; then
-            log "The clone directory ${NAME}-${GIT_SHA} already exists, removing..."
-            rm -rf ${NAME}-${GIT_SHA}
-        fi
-        log "Cloning ${NAME}-${GIT_SHA} ..."
-        git clone ${GIT_URL} ${NAME}-${GIT_SHA}
-        cd ${NAME}-${GIT_SHA}
-        log "Checking out the revision ${GIT_REF} with the SHA ${GIT_SHA} ..."
-        git checkout -b sat-branch ${GIT_SHA}
-	if [ "x${POST_CLONE}" != "x" ]; then
-		log "Running post clone code for ${NAME}-${GIT_SHA} ..."
-		${POST_CLONE}
-	fi
-        log "Removing .git directory from ${NAME}-${GIT_SHA} ..."
-        rm -rf .git
-        cd ..
-        log "Generating source archive for ${NAME}-${GIT_SHA} ..."
-        tar cfj ${SOURCES}/${NAME}-${GIT_SHA}.tar.bz2 ${NAME}-${GIT_SHA}
+    # Making sure there is nothing in our way
+    if [ -e ${NAME}-${GIT_SHA} ]; then
+        log "The clone directory ${NAME}-${GIT_SHA} already exists, removing..."
         rm -rf ${NAME}-${GIT_SHA}
-        touch ${STAMPS}/${NAME}-${GIT_SHA}.fetch
+    fi
+    log "Cloning ${NAME}-${GIT_SHA} ..."
+    git clone ${GIT_URL} ${NAME}-${GIT_SHA}
+    cd ${NAME}-${GIT_SHA}
+    log "Checking out the revision ${GIT_REF} with the SHA ${GIT_SHA} ..."
+    git checkout -b sat-branch ${GIT_SHA}
+    if [ "x${POST_CLONE}" != "x" ]; then
+        log "Running post clone code for ${NAME}-${GIT_SHA} ..."
+        ${POST_CLONE}
+    fi
+    log "Removing .git directory from ${NAME}-${GIT_SHA} ..."
+    rm -rf .git
+    cd ..
+    log "Generating source archive for ${NAME}-${GIT_SHA} ..."
+    tar cfj ${SOURCES}/${NAME}-${GIT_SHA}.tar.bz2 ${NAME}-${GIT_SHA}
+    rm -rf ${NAME}-${GIT_SHA}
+    touch ${STAMPS}/${NAME}-${GIT_SHA}.fetch
     fi
 }
 
@@ -305,19 +305,19 @@ function unpack {
     # Use 'auto' mode decompression.  Replace with a switch if tar doesn't support -a
     ARCHIVE=$(ls ${SOURCES}/$1.tar.*)
     case ${ARCHIVE} in
-	*.bz2)
-	    echo "archive type bz2"
-	    TYPE=j
-	    ;;
-	*.gz)
-	    echo "archive type gz"
-	    TYPE=z
-	    ;;
-	*)
-	    echo "Unknown archive type of $1"
-	    echo ${ARCHIVE}
-	    exit 1
-	    ;;
+    *.bz2)
+        echo "archive type bz2"
+        TYPE=j
+        ;;
+    *.gz)
+        echo "archive type gz"
+        TYPE=z
+        ;;
+    *)
+        echo "Unknown archive type of $1"
+        echo ${ARCHIVE}
+        exit 1
+        ;;
     esac
     ${TAR} xf${TYPE}${TARFLAGS} ${SOURCES}/$1.tar.*
 }
@@ -339,47 +339,47 @@ fetch ${NEWLIB} ftp://sourceware.org/pub/newlib/${NEWLIB}.tar.gz
 fetch ${GDB} ${GDBURL}
 
 if [ ${OOCD_EN} != 0 ]; then
-	if [ "x${OOCD_GIT}" == "x" ]; then
-		fetch ${OOCD} http://sourceforge.net/projects/openocd/files/openocd/0.6.1/${OOCD}.tar.bz2
-	else
-		clone oocd ${OOCD_GIT} git://openocd.git.sourceforge.net/gitroot/openocd/openocd ./bootstrap
-	fi
+    if [ "x${OOCD_GIT}" == "x" ]; then
+        fetch ${OOCD} http://sourceforge.net/projects/openocd/files/openocd/0.6.1/${OOCD}.tar.bz2
+    else
+        clone oocd ${OOCD_GIT} git://openocd.git.sourceforge.net/gitroot/openocd/openocd ./bootstrap
+    fi
 fi
 
 if [ ${LIBSTM32_EN} != 0 ]; then
-	if [ "x${LIBCMSIS_GIT}" == "x" ]; then
-		log "There is no libcmsis stable release download server yet!"
-		exit 1
-		#fetch ${LIBCMSIS} http://.../${LIBCMSIS}.tar.bz2
-	else
-		clone libcmsis ${LIBCMSIS_GIT} git://github.com/esden/libcmsis.git
-	fi
+    if [ "x${LIBCMSIS_GIT}" == "x" ]; then
+        log "There is no libcmsis stable release download server yet!"
+        exit 1
+        #fetch ${LIBCMSIS} http://.../${LIBCMSIS}.tar.bz2
+    else
+        clone libcmsis ${LIBCMSIS_GIT} git://github.com/esden/libcmsis.git
+    fi
 
-	if [ "x${LIBSTM32_GIT}" == "x" ]; then
-		log "There is no libstm32 stable release download server yet!"
-		exit 1
-		#fetch ${LIBSTM32} http://.../${LIBSTM32}.tar.bz2
-	else
-		clone libstm32 ${LIBSTM32_GIT} git://github.com/esden/libstm32.git
-	fi
+    if [ "x${LIBSTM32_GIT}" == "x" ]; then
+        log "There is no libstm32 stable release download server yet!"
+        exit 1
+        #fetch ${LIBSTM32} http://.../${LIBSTM32}.tar.bz2
+    else
+        clone libstm32 ${LIBSTM32_GIT} git://github.com/esden/libstm32.git
+    fi
 
-	if [ "x${LIBSTM32USB_GIT}" == "x" ]; then
-		log "There is no libstm32usb stable release download server yet!"
-		exit 1
-		#fetch ${LIBSTM32USB} http://.../${LIBSTM32USB}.tar.bz2
-	else
-		clone libstm32usb ${LIBSTM32USB_GIT} git://github.com/esden/libstm32usb.git
-	fi
+    if [ "x${LIBSTM32USB_GIT}" == "x" ]; then
+        log "There is no libstm32usb stable release download server yet!"
+        exit 1
+        #fetch ${LIBSTM32USB} http://.../${LIBSTM32USB}.tar.bz2
+    else
+        clone libstm32usb ${LIBSTM32USB_GIT} git://github.com/esden/libstm32usb.git
+    fi
 fi
 
 if [ ${LIBOPENCM3_EN} != 0 ]; then
-	if [ "x${LIBOPENCM3_GIT}" == "x" ]; then
-		log "There is no libopencm3 stable release download server yet!"
-		exit 1
-		#fetch ${LIBOPENCM3} http://.../${LIBOPENCM3}.tar.bz2
-	else
-		clone libopencm3 ${LIBOPENCM3_GIT} git://github.com/libopencm3/libopencm3.git
-	fi
+    if [ "x${LIBOPENCM3_GIT}" == "x" ]; then
+        log "There is no libopencm3 stable release download server yet!"
+        exit 1
+        #fetch ${LIBOPENCM3} http://.../${LIBOPENCM3}.tar.bz2
+    else
+        clone libopencm3 ${LIBOPENCM3_GIT} git://github.com/libopencm3/libopencm3.git
+    fi
 fi
 
 cd ${SUMMON_DIR}
@@ -397,13 +397,13 @@ if [ ! -e ${STAMPS}/${BINUTILS}.build ]; then
     cd build
     log "Configuring ${BINUTILS}"
     ../${BINUTILS}/configure --target=${TARGET} \
-                             --prefix=${PREFIX} \
-                             --enable-multilib \
-                             --with-gnu-as \
-                             --with-gnu-ld \
-                             --disable-nls \
-                             --disable-werror \
-                             ${BINUTILFLAGS}
+                 --prefix=${PREFIX} \
+                 --enable-multilib \
+                 --with-gnu-as \
+                 --with-gnu-ld \
+                 --disable-nls \
+                 --disable-werror \
+                 ${BINUTILFLAGS}
     log "Building ${BINUTILS}"
     make ${MAKEFLAGS}
     install ${BINUTILS} install
@@ -423,40 +423,40 @@ if [ ! -e ${STAMPS}/${GCC}-${NEWLIB}.build ]; then
     ln -f -s `pwd`/${NEWLIB}/libgloss ${GCC}
 
     if [ ${DEFAULT_TO_CORTEX_M3} == 0 ] ; then
-	log "Patching gcc to add multilib support"
-	cd ${GCC}
-	patch -p0 -i ../patches/patch-gcc-config-arm-t-arm-elf.diff
-	patch -p0 -i ../patches/patch-libgcc-divide-exceptions.diff
-	cd ..
+    log "Patching gcc to add multilib support"
+    cd ${GCC}
+    patch -p0 -i ../patches/patch-gcc-config-arm-t-arm-elf.diff
+    patch -p0 -i ../patches/patch-libgcc-divide-exceptions.diff
+    cd ..
     fi
 
     cd build
     if [ "X${GCC_CC}" != "X" ] ; then
-	    export GLOBAL_CC=${CC}
-	    log "Overriding the default compiler with: \"${GCC_CC}\""
-	    export CC=${GCC_CC}
+        export GLOBAL_CC=${CC}
+        log "Overriding the default compiler with: \"${GCC_CC}\""
+        export CC=${GCC_CC}
     fi
 
     log "Configuring ${GCC} and ${NEWLIB}"
     ../${GCC}/configure --target=${TARGET} \
-                      --prefix=${PREFIX} \
-                      --enable-multilib \
-                      --enable-languages="c,c++" \
-                      --with-newlib \
-                      --with-gnu-as \
-                      --with-gnu-ld \
-                      --disable-nls \
-                      --disable-shared \
-		      --disable-threads \
-                      --with-headers=newlib/libc/include \
-		      --disable-libssp \
-		      --disable-libstdcxx-pch \
-		      --disable-libmudflap \
-		      --disable-libgomp \
-                      --disable-werror \
-		      --with-system-zlib \
-		      --disable-newlib-supplied-syscalls \
-		      ${GCCFLAGS}
+              --prefix=${PREFIX} \
+              --enable-multilib \
+              --enable-languages="c,c++" \
+              --with-newlib \
+              --with-gnu-as \
+              --with-gnu-ld \
+              --disable-nls \
+              --disable-shared \
+              --disable-threads \
+              --with-headers=newlib/libc/include \
+              --disable-libssp \
+              --disable-libstdcxx-pch \
+              --disable-libmudflap \
+              --disable-libgomp \
+              --disable-werror \
+              --with-system-zlib \
+              --disable-newlib-supplied-syscalls \
+              ${GCCFLAGS}
     log "Building ${GCC} and ${NEWLIB}"
     make ${MAKEFLAGS}
     install ${GCC} install
@@ -464,9 +464,9 @@ if [ ! -e ${STAMPS}/${GCC}-${NEWLIB}.build ]; then
     log "Cleaning up ${GCC} and ${NEWLIB}"
 
     if [ "X${GCC_CC}" != "X" ] ; then
-	    unset CC
-	    CC=${GLOBAL_CC}
-	    unset GLOBAL_CC
+        unset CC
+        CC=${GLOBAL_CC}
+        unset GLOBAL_CC
     fi
 
     touch ${STAMPS}/${GCC}-${NEWLIB}.build
@@ -478,10 +478,10 @@ if [ ! -e ${STAMPS}/${GDB}.build ]; then
     cd build
     log "Configuring ${GDB}"
     ../${GDB}/configure --target=${TARGET} \
-                      --prefix=${PREFIX} \
-                      --enable-multilib \
-                      --disable-werror \
-		      ${GDBFLAGS}
+              --prefix=${PREFIX} \
+              --enable-multilib \
+              --disable-werror \
+              ${GDBFLAGS}
     log "Building ${GDB}"
     make ${MAKEFLAGS}
     install ${GDB} install
@@ -503,21 +503,22 @@ if [ ! -e ${STAMPS}/${OOCD}.build ]; then
     CFLAGS="${CFLAGS} ${OOCD_CFLAGS}" \
     LDFLAGS="${LDFLAGS} ${OOCD_LDFLAGS}" \
     ../${OOCD}/configure --enable-maintainer-mode \
-				 --disable-option-checking \
-				 --disable-werror \
-				 --prefix=${PREFIX} \
-				 --enable-dummy \
-				 --enable-ft2232_libftdi \
-				 --enable-usb_blaster_libftdi \
-				 --enable-ep93xx \
-				 --enable-at91rm9200 \
-				 --enable-presto_libftdi \
-				 --enable-usbprog \
-				 --enable-jlink \
-				 --enable-vsllink \
-				 --enable-rlink \
-				 --enable-arm-jtag-ew \
-				 --enable-stlink
+                 --disable-option-checking \
+                 --disable-werror \
+                 --prefix=${PREFIX} \
+                 --enable-dummy \
+                 --enable-ft2232_libftdi \
+                 --enable-usb_blaster_libftdi \
+                 --enable-ep93xx \
+                 --enable-at91rm9200 \
+                 --enable-presto_libftdi \
+                 --enable-usbprog \
+                 --enable-jlink \
+                 --enable-vsllink \
+                 --enable-rlink \
+                 --enable-arm-jtag-ew \
+                 --enable-stlink \
+                 --enable-ti-icdi
     log "Building ${OOCD}"
     make ${MAKEFLAGS}
     install ${OOCD} install
